### ISSUE TITLE
Error installing reactivated on WSL2/Windows with Nix: invalid database permissions

### ISSUE THREAD

**Issue by clayheaton** [silviogutierrez/reactivated#267]
Following instructions to install reactivated on WSL2 leads to an error with data directory permissions:

```
running bootstrap script ... 2023-05-26 15:08:24.140 UTC [141544] FATAL:  data directory "/mnt/c/Users/cheaton/projects/react/test/.venv/postgresql" has invalid permissions
```

The more complete error:

```
creating directory /mnt/c/Users/cheaton/projects/react/test/.venv/postgresql ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... UTC
creating configuration files ... ok
running bootstrap script ... 2023-05-26 15:11:01.476 UTC [146151] FATAL:  data directory "/mnt/c/Users/cheaton/projects/react/test/.venv/postgresql" has invalid permissions
2023-05-26 15:11:01.476 UTC [146151] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
child process exited with exit code 1
initdb: removing data directory "/mnt/c/Users/cheaton/projects/react/test/.venv/postgresql"
Traceback (most recent call last):
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 230, in ensure_connection
    self.connect()
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 25, in inner
    return func(*args, **kwargs)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 211, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 25, in inner
    return func(*args, **kwargs)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 199, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server on socket "/run/user/1000//reactivated/c2f17a4afaa1040356f83ab82317ebb7/.s.PGSQL.1" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/cheaton/projects/react/test/manage.py", line 22, in <module>
    main()
  File "/mnt/c/Users/cheaton/projects/react/test/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 417, in execute
    output = self.handle(*args, **options)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 90, in wrapped
    res = handle_func(*args, **kwargs)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/core/management/base.py", line 438, in check
    all_issues = checks.run_checks(
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/core/checks/registry.py", line 77, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/core/checks/model_checks.py", line 34, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 1307, in check
    *cls._check_indexes(databases),
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/db/models/base.py", line 1699, in _check_indexes
    connection.features.supports_covering_indexes or
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/db/backends/postgresql/features.py", line 84, in is_postgresql_11
    return self.connection.pg_version >= 110000
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 339, in pg_version
    with self.temporary_connection():
  File "/nix/store/r8hi2lpzycparplcq0y663c43866f9bz-python3-3.9.13/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 614, in temporary_connection
    with self.cursor() as cursor:
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 25, in inner
    return func(*args, **kwargs)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 270, in cursor
    return self._cursor()
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 246, in _cursor
    self.ensure_connection()
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 25, in inner
    return func(*args, **kwargs)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 230, in ensure_connection
    self.connect()
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 230, in ensure_connection
    self.connect()
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 25, in inner
    return func(*args, **kwargs)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 211, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 25, in inner
    return func(*args, **kwargs)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 199, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/mnt/c/Users/cheaton/projects/react/test/.venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server on socket "/run/user/1000//reactivated/c2f17a4afaa1040356f83ab82317ebb7/.s.PGSQL.1" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
```

**Comment by silviogutierrez** [comment]
Thanks for the report. Could you edit `node_modules/.bin/setup_environment.sh` to play around with permissions right above line 26? That's after the data dir has been created by `initdb` but before Postgres starts.

Try adding `chmod -R 0777 $POSTGRESQL_DATA`. You can then `rm -rf .venv` and just run `nix-shell` again to see.

**Comment by clayheaton** [comment]
Still an error -- there's another permission issue, evidently.

```
[notice] A new release of pip available: 22.1.2 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
chmod: cannot access '/mnt/c/Users/cheaton/projects/reactest/reactivated/.venv/postgresql': No such file or directory
The files belonging to this database system will be owned by user "clay".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /mnt/c/Users/cheaton/projects/reactest/reactivated/.venv/postgresql ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting default time zone ... UTC
creating configuration files ... ok
running bootstrap script ... 2023-05-26 20:13:17.262 UTC [24652] FATAL:  data directory "/mnt/c/Users/cheaton/projects/reactest/reactivated/.venv/postgresql" has invalid permissions
2023-05-26 20:13:17.262 UTC [24652] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
child process exited with exit code 1
initdb: removing data directory "/mnt/c/Users/cheaton/projects/reactest/reactivated/.venv/postgresql"
```
I don't really have time to dig into it right now but might take a look this weekend.

**Comment by silviogutierrez** [comment]
Got it. We don't support Windows, but it'd be nice to get some input and maybe get it working officially.

Also check out this: https://superuser.com/questions/1323645/unable-to-change-file-permissions-on-ubuntu-bash-for-windows-10

**Comment by silviogutierrez** [comment]
Hi there, closing this out but feel free to reopen if you get more info and we can investigate.

**Comment by clayheaton** [comment]
That's fine - I'm not sure it's a Windows issue since I was running in an Ubuntu VM. I tried the various fixes and continued to run into an error with the postgres permissions. If I get a chance, I'll try it on a cloud VM.

**Comment by silviogutierrez** [comment]
@clayheaton : odd, I do an ubuntu VM for the integration test, so no issues. Look at .github/workflows if you're curious.

In the future, I may revamp the self-hosted pg instance. You can also just remove all those lines and host your own database without issues.
