### ISSUE TITLE
Error with project postgresql connection with nix on Mac

### ISSUE THREAD

**Issue by letam** [silviogutierrez/reactivated#383]
Attempted to set up the project on a Mac with `nix-shell -E "$(curl -L https://reactivated.io/install/)"` and I run into this error: 

```
...
creating directory /Users/user/proj/.venv/postgresql ... ok 
creating subdirectories ... ok 
selecting dynamic shared memory implementation ... posix 
selecting default max_connections ... 100 
selecting default shared_buffers ... 128MB 
selecting default time zone ... UTC 
creating configuration files ... ok 
running bootstrap script ... ok 
performing post-bootstrap initialization ... ok 
syncing data to disk ... ok 
 
initdb: warning: enabling "trust" authentication for local connections 
You can change this by editing pg_hba.conf or using the option -A, or 
--auth-local and --auth-host, the next time you run initdb. 
 
Success. You can now start the database server using: 
 
    pg_ctl -D /Users/user/proj/.venv/postgresql -l logfile start 
 
[15/Nov/2024 16:44:09,361] Generating interfaces and client side code 
[15/Nov/2024 16:44:10,825] Finished generating. 
Traceback (most recent call last): 
  File "/Users/user/proj/.venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection 
    self.connect() 
  File "/Users/user/proj/.venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner 
    return func(*args, **kwargs) 
           ^^^^^^^^^^^^^^^^^^^^^ 
  File "/Users/user/proj/.venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect 
    self.connection = self.get_new_connection(conn_params) 
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/Users/user/proj/.venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner 
    return func(*args, **kwargs) 
           ^^^^^^^^^^^^^^^^^^^^^ 
  File "/Users/user/proj/.venv/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 277, in get_new_connection 
    connection = self.Database.connect(**conn_params) 
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/Users/user/proj/.venv/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect 
  File "/Users/user/proj/.venv/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect 
    raise last_ex.with_traceback(None) 
psycopg.OperationalError: connection is bad: Unix-domain socket path "/private/tmp/nix-shell-46168-0/nix-shell-46183-0/nix-shell-46766-0/reactivated/2a622b85e4ccceb81dd33192e8db65aa/.s.PGSQL.1" is too long (maximum 103 bytes) 
...
```

**Comment by silviogutierrez** [comment]
Hey Tam,

Not much we can do here. For some reason, your nix paths are deeply nested and instead of creating in `/tmp/` it seems to create in some weirdly recursive nix-shell path.

On a basic MacOS/nix install, my path is:
```
echo $PGHOST
/tmp/reactivated/81331819c8072d6a4a17da9b2293b7d2
```

Yours is much longer for some reason.

**Comment by viktorvillalobos** [comment]
Same error here:

MacOS Sequoia
Nix (Nix) 2.25.2

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/2abda1a8-6611-498e-829c-8f9215402aff">

**Comment by silviogutierrez** [comment]
Sounds to me like MacOS 15 now shadows `/tmp/` somehow, or maybe Nix does. I'll have to investigate.

**Comment by silviogutierrez** [comment]
I think #384 might have fixed it. Can you try again?

**Comment by letam** [comment]
Seems to be fixed after changing to refer to the `/tmp` path directly, in #384. Thanks!

**Comment by silviogutierrez** [comment]
Great, closing this out. Thanks for the report.

**Comment by viktorvillalobos** [comment]
Thank you very much, this worked great!
